blank_issues_enabled: false
contact_links:
  - name: Open a Discussion
    url: https://github.com/canton7/stylet/discussions/new
    about: If you've got a question, suggestion, or something you're not sure about, please open a discussion.